spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/localdb
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none  # create 可以在测试环境配置
      naming: # 无修改命名
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 10001

feign:
  client:
    config:
      default:
        loggerLevel: FULL
logging:
  level:
    com:
      funnyx:
        order: debug
